export const APP_CONFIG = {
  TELEGRAM_ADMIN_ID: import.meta.env.VITE_TELEGRAM_ADMIN_ID || "1085949511",
  ADMIN_ACCESS_CODE: import.meta.env.VITE_ADMIN_ACCESS_CODE || "COREDEVELOPER1991",
  STORE_NAME: "PRIME Commerce",
  STORE_DISCLAIMER: "USAGE OF THIS SYSTEM IS PROPRIETARY. DO NOT DISTRIBUTE OR COPY.",
};
