import { useEffect, useState } from "react";
import { addDoc, collection, deleteDoc, doc, onSnapshot, orderBy, query, serverTimestamp, updateDoc } from "firebase/firestore";
import { db } from "@/lib/firebase.ts";
import { Plus, Trash2 } from "lucide-react";

type Discount = { id: string; code: string; value: number; type: "fixed" | "percent"; minSubtotal: number; active: boolean };

export default function AdminDiscountsPage() {
  const [items, setItems] = useState<Discount[]>([]);
  const [code, setCode] = useState(""); const [value, setValue] = useState(""); const [minSubtotal, setMinSubtotal] = useState(""); const [type, setType] = useState<Discount["type"]>("percent");
  useEffect(() => onSnapshot(query(collection(db,"discounts"), orderBy("createdAt","desc")), s => setItems(s.docs.map(d=>({id:d.id,...(d.data() as Omit<Discount,"id">)})))), []);
  const add = async () => { if(!code.trim() || Number(value)<0) return; await addDoc(collection(db,"discounts"),{code:code.trim().toUpperCase(),value:Number(value),type,minSubtotal:Number(minSubtotal)||0,active:true,createdAt:serverTimestamp(),updatedAt:serverTimestamp()}); setCode("");setValue("");setMinSubtotal(""); };
  return <section className="p-3 sm:p-5 max-w-3xl mx-auto" style={{fontFamily:"'Roboto Condensed', sans-serif"}}><header className="mb-4"><p className="text-[10px] tracking-[.2em] text-neutral-400">ADMIN / PRICING</p><h1 className="text-2xl">DISCOUNTS</h1></header><div className="bg-white border border-neutral-200 rounded-xl p-3 mb-3 grid grid-cols-[1fr_75px_75px_85px_38px] gap-2"><input className="border border-neutral-200 rounded-lg px-2 text-sm" placeholder="Promo code" value={code} onChange={e=>setCode(e.target.value)}/><input className="border border-neutral-200 rounded-lg px-2 text-sm" type="number" min="0" placeholder="Value" value={value} onChange={e=>setValue(e.target.value)}/><select className="border border-neutral-200 rounded-lg px-2 text-sm" value={type} onChange={e=>setType(e.target.value as Discount["type"])}><option value="percent">%</option><option value="fixed">Fixed</option></select><input className="border border-neutral-200 rounded-lg px-2 text-sm" type="number" min="0" placeholder="Min ₱" value={minSubtotal} onChange={e=>setMinSubtotal(e.target.value)}/><button onClick={add} className="bg-black text-white rounded-lg flex items-center justify-center"><Plus size={16}/></button></div><div className="space-y-2">{items.map(d=><div key={d.id} className="bg-white border border-neutral-200 rounded-xl p-3 flex items-center gap-3"><div className="flex-1"><div className="font-semibold text-sm tracking-wide">{d.code}</div><div className="text-xs text-neutral-400">{d.type === "percent"?`${d.value}%`:`₱${d.value.toLocaleString()}`} · Min ₱{d.minSubtotal.toLocaleString()} · {d.active?"Active":"Inactive"}</div></div><button onClick={()=>updateDoc(doc(db,"discounts",d.id),{active:!d.active,updatedAt:serverTimestamp()})} className="text-xs border rounded-lg px-2 py-1">{d.active?"Disable":"Enable"}</button><button onClick={()=>deleteDoc(doc(db,"discounts",d.id))} className="text-neutral-400 hover:text-red-600"><Trash2 size={15}/></button></div>)}</div></section>;
}
